config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  devise_for :users , controllers: {registrations: 'registrations'}

 

  resources :books

  resources :categories

  resources :authors

  root 'home#index'

end

app/models/author.rb
class Author < ActiveRecord::Base
	has_many :books
	#validates :author, uniqueness: { messages: "No puede estar repetido"}, presence: { messages: "Campo Obligatorio"}
end

app/models/book.rb
class Book < ActiveRecord::Base
	belongs_to :author
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :books
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  	
  protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:email, :password, :password_confirmation, :iduser, :name, :lastname, :typeuser, :birthday, :address) } 
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Autor fue creado Satisfactoriamente.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Autor fue Actualizado Satisfactoriamente.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @gift = Author.find(params[:id])
    @author.destroy
    respond_to do |format|
      #format.html { redirect_to authors_url, notice: 'Autor fue Eliminado Satisfactoriamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:name)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Libro fue creado Satisfactoriamente.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Libro fue actualizado Satisfactoriamente.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Libro fue Eliminado Satisfactoriamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:book_id, :author_id, :category_id, :title, :description)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Categoria fue creado satisfactoriamente.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Categoria fue Actualizado satisfactoriamente.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Categoria fue Eliminado satisfactoriamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
	def new
		super
	end

	def create
		super
	end

	def update
		super
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/authors/_form.html.erb
<%= form_for(@author) do |f| %>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% @author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<table>
    <tbody>
      <tr>
        <th colspan="2">Información:</th>
      </tr>
      <tr>
        <td class="a1" width="23%"><div><%= f.label :name, "Nombre :" %></div></td>
        <td class="a1" width="77%"><%= f.text_field :name, autofocus: true %></td>
        </tr>
      <tr>
        <td  class="a1" colspan="2"><%= f.submit "Actualizar" %></td>
        </tr>

    </tbody>
</table>

<% end %>

app/views/authors/edit.html.erb
<h1>Editar Autor</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @author %> |
<%= link_to 'Atras', authors_path %>

app/views/authors/index.html.erb
<h1>Lista de Autores</h1>

<table>
  <thead>
    <tr>
      <th>Nombres</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.name %></td>
        <td><%= link_to image_tag("icoVisualizar.gif", :alt => "Mostrar", :title => "Mostrar"), author %></td>
        <td><%= link_to image_tag("icoEditar.gif", :alt => "Editar", :title => "Editar"), edit_author_path(author) %></td>
        <td><%= link_to image_tag("icoEliminar.gif", :alt => "Eliminar", :title => "Eliminar"), author, method: :delete, data: { confirm: '¿Esta Seguro de Eliminar?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Autor', new_author_path %>

app/views/authors/new.html.erb
<h1>Nuevo Autor</h1>

<%= render 'form' %>

<%= link_to 'Atras', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>


<table>
    <tbody>
      <tr>
        <th colspan="2">Información:</th>
      </tr>
      <tr>
        <td class="a1" width="23%"><strong>Nombre :</strong></td>
        <td class="a1" width="77%"><%= @author.name %></td>
        </tr>

    </tbody>
</table>

<%= link_to 'Modificar', edit_author_path(@author) %> |
<%= link_to 'Atras', authors_path %>

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<table>
    <tbody>
      <tr>
        <th colspan="2">Información:</th>
      </tr>
      <tr>
        <td class="a1" width="23%"><%= f.label :book_id, "Codigo:" %></td>
        <td class="a1" width="77%"><%= f.text_field :book_id %></td>
      </tr>
      <tr>
        <td class="a1" width="23%"><%= f.label :Titulo, "Titulo" %></td>
        <td class="a1" width="77%"><%= f.text_field :title %></td>
      </tr>
      <tr>
        <td class="a1" width="23%"><%= f.label :author_id, "Autor" %></td>
        <td class="a1" width="77%"><%= f.collection_select :author_id, Author.all, :id, :name, :prompt => true %></td>
      </tr>
      <tr>
        <td class="a1" width="23%"><%= f.label :category_id, "Cateroria" %></td>
        <td class="a1" width="77%"><%= f.collection_select :category_id, Category.all, :id, :name, :prompt => true %></td>
      </tr>
      <tr>
        <td class="a1" width="23%"><%= f.label :description %></td>
        <td class="a1" width="77%"><%= f.text_field :description %></td>
      </tr>                  
      <tr>
        <td  class="a1" colspan="2"><div class="actions"><%= f.submit "Grabar" %></div></td>
        </tr>

    </tbody>
</table>



<% end %>

app/views/books/edit.html.erb
<h1>Editar Libro</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @book %> |
<%= link_to 'Atras', books_path %>

app/views/books/index.html.erb
<h1>Lista de Libros</h1>

<table>
  <thead>
    <tr>
      <th>Código</th>
      <th>Título</th>
      <th>Descripción</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <%# @book.author.name  %>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.book_id %></td>
        <td><%= book.title %></td>
        <td><%= book.description %></td>
        <td><%= link_to image_tag("icoVisualizar.gif", :alt => "Mostrar", :title => "Mostrar"), book %></td>
        <td><%= link_to image_tag("icoEditar.gif", :alt => "Editar", :title => "Editar"), edit_book_path(book) %></td>
        <td><%= link_to image_tag("icoEliminar.gif", :alt => "Eliminar", :title => "Eliminar"), book, method: :delete, data: { confirm: '¿Esta Seguro de Eliminar?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Libro', new_book_path %>

app/views/books/new.html.erb
<h1>Nuevo Libro</h1>

<%= render 'form' %>

<%= link_to 'Atras', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Título:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Descripción:</strong>
  <%= @book.description %>
</p>

<%= link_to 'Editar', edit_book_path(@book) %> |
<%= link_to 'Atras', books_path %>

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, "Nombre" %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit "Grabar" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editar Categoría</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @category %> |
<%= link_to 'Atras', categories_path %>

app/views/categories/index.html.erb
<h1>Lista de Categorias</h1>

<table>
  <thead>
    <tr>
      <th>Nombres</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>

        <td><%= link_to image_tag("icoVisualizar.gif", :alt => "Mostrar", :title => "Mostrar"), category %></td>
        <td><%= link_to image_tag("icoEditar.gif", :alt => "Editar", :title => "Editar"), edit_category_path(category) %></td>
        <td><%= link_to image_tag("icoEliminar.gif", :alt => "Eliminar", :title => "Eliminar"), category, method: :delete, data: { confirm: '¿Esta Seguro de Eliminar?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva Categoría', new_category_path %>

app/views/categories/new.html.erb
<h1>Nueva categoria</h1>

<%= render 'form' %>

<%= link_to 'Atras', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Editar', edit_category_path(@category) %> |
<%= link_to 'Atras', categories_path %>

app/views/home/index.html.erb
<h1>Biblioteca</h1>

<% if user_signed_in? %>
	<%= image_tag "libreria1.jpg", :alt => "Libreria", :title => "Libreria", width: 640, height: 480 %>
<% else %>

<%= image_tag "libreria1.jpg", :alt => "Libreria", :title => "Libreria", width: 960, height: 720 %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Loanbook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%# javascript_include_tag 'application', 'all' %>
  <%= csrf_meta_tags %>
</head>

<body>
<div id="container">
	
<div id="header" >
<h1><a href="/">Loan<strong>Books</strong></a></h1>
<h2>El placer de leer un Libro</h2>
<img src="/assets/banner001.jpg" width="460" height="100" alt="banner001" />
        
        <div class="clear"></div>
  </div>
    
  <div id="nav">
    	<ul class="sf-menu dropdown">
        	<li><a href="http://localhost:3000/">Inicio</a></li>
            <li><a href="http://localhost:3000/">Centro de Información</a></li>
          <li><a href="http://localhost:3000/">Preguntas Frecuentes</a></li>
            <li><a href="http://localhost:3000/">Ayuda</a></li>
        </ul>
  </div>
    
    <div>
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>        

      <p class="navbar-text pull-right">
      <% if user_signed_in? %>
        Bienvenido: <strong><%= "#{current_user.name} #{current_user.lastname}" %></strong>.
        <%= link_to 'Ver Perfil', edit_user_registration_path, :class => 'navbar-link' %> |
        <%= link_to "Salir", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
      <% else %>
        <%= link_to "Registrarse", new_user_registration_path, :class => 'navbar-link'  %> |
        <%= link_to "Ingresar", new_user_session_path, :class => 'navbar-link'  %>
      <% end %>
      
    </div>

<div id="body">

        <div id="content">
           <%= yield %> 
        </div>


        <% if user_signed_in? %>

        <div class="sidebar">
            <ul>	
               <li>
                    <h4><span>Usuarios</span></h4>
                    <ul class="blocklist">
                        <!--<li><%= link_to "Registro", new_user_registration_path, :class => 'navbar-link'  %></li> -->
                        <li><a href="http://localhost:3000/users/sign_up">Registro</a></li>
                        <li><a href="#">Busqueda</a></li
                    ></ul>
              </li>
                
               <li>
                    <h4><span>Libros</span></h4>
                    <ul class="blocklist">
                        <li><a href="http://localhost:3000/books">Registro</a></li>
                        <li><a href="#">Busqueda</a></li>
                        <li><a href="http://localhost:3000/authors">Autores</a></li>
                        <li><a href="http://localhost:3000/categories">Categorias</a></li>
                    </ul>
              </li>
                
                <li>
                    <h4><span>Prestamos</span></h4>
                    <ul class="blocklist">
                        <li><a href="#">Registro</a></li>
                        <li><a href="#">Busqueda</a></li
                    ></ul>
                </li>
                
                <li>
                    <h4><span>Consultas</span></h4>
                    <ul class="blocklist">
                        <li><a href="#">Pendientes</a></li>
                        <li><a href="#">Vencidos</a></li
                    ></ul>
                </li>           
                               
          </ul> 
        </div>
        <% end %>

    	<div class="clear"></div>
    </div>


    <div id="footer">
        <div class="footer-content">
    
                <span class="sitename">LoanBooks.com</span>
                 <p class="footer-links">
                    <a href="index.html">Inicio</a>
                    <a href="examples.html">Centro de Información</a>
                    <a href="#">Preguntas Frecuentes</a>
                    <a href="#">Ayuda</a>
    				<a href="#container" class="backtotop">Back to top</a>
               	 </p>
                 <div class="clear"></div>
        </div>
        <div class="footer-bottom">
            <p>&copy; YourSite 2014. Website Design by <a href="http://www.spyka.net">Grupo LoanBooks</a></p>
        </div>
    </div>

</div>
</body>


</html>